language: python
matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.6
        - os: linux
          python: nightly
        - os: osx
          language: generic
          name: Python 3
          before_install:
            - pip install virtualenv
            - virtualenv venv -p python3
            - source venv/bin/activate
          env: PYTHON=python
        - os: osx
          language: generic
          name: System Python (2.7)
          before_install:
            - pip install virtualenv
            - virtualenv venv -p python
            - source venv/bin/activate
script: "./run-tests-ci.sh"
notifications:
  email: false
