language: python
# OSX workaround from
# https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-195620855
matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.6
        - os: linux
          python: nightly
        # Use generic language for osx
        - os: osx
          language: generic
# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
# Python 3 seems to be installed by default
script: "./run-tests-ci.sh"
notifications:
  email: false
